-- MySQL Script generated by MySQL Workbench
-- Wed Sep  5 16:12:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema matcha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `matcha` ;

-- -----------------------------------------------------
-- Schema matcha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matcha` DEFAULT CHARACTER SET utf8mb4 ;
USE `matcha` ;

-- -----------------------------------------------------
-- Table `matcha`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`users` ;

CREATE TABLE IF NOT EXISTS `matcha`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` BINARY(60) NOT NULL,
  `sex_pref` SET('Heterosexual', 'Homosexual', 'Bisexual') NULL DEFAULT 'Bisexual',
  `gender` SET('Female', 'Male') NULL,
  `position` TEXT(200) NULL,
  `age` DATE NULL,
  `lastonline` DATETIME NULL,
  `biography` TEXT(500) NULL,
  `reports` INT NOT NULL DEFAULT 0,
  `verifyhash` VARCHAR(64) NOT NULL,
  `popularity` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`tags` ;

CREATE TABLE IF NOT EXISTS `matcha`.`tags` (
  `idtags` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`tag_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`tag_user` ;

CREATE TABLE IF NOT EXISTS `matcha`.`tag_user` (
  `iduser` INT NOT NULL,
  `idtag` INT NOT NULL,
  INDEX `fk_to_user_idx` (`iduser` ASC),
  INDEX `fk_to_tag_idx` (`idtag` ASC),
  CONSTRAINT `fk_to_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `matcha`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_to_tag`
    FOREIGN KEY (`idtag`)
    REFERENCES `matcha`.`tags` (`idtags`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`pictures` ;

CREATE TABLE IF NOT EXISTS `matcha`.`pictures` (
  `idOwner` INT NOT NULL,
  `location` CHAR(37) NOT NULL,
  `isMain` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_pic_to_users_idx` (`idOwner` ASC),
  UNIQUE INDEX `location_UNIQUE` (`location` ASC),
  CONSTRAINT `fk_pic_to_users`
    FOREIGN KEY (`idOwner`)
    REFERENCES `matcha`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`seen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`seen` ;

CREATE TABLE IF NOT EXISTS `matcha`.`seen` (
  `iduser_watcher` INT NOT NULL,
  `iduser_watched` INT NOT NULL,
  `liked` INT NOT NULL DEFAULT 0,
  `notificated` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_like_to_user_idx` (`iduser_watcher` ASC),
  INDEX `fk_watched_idx` (`iduser_watched` ASC),
  CONSTRAINT `fk_watcher`
    FOREIGN KEY (`iduser_watcher`)
    REFERENCES `matcha`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watched`
    FOREIGN KEY (`iduser_watched`)
    REFERENCES `matcha`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`blocked_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`blocked_users` ;

CREATE TABLE IF NOT EXISTS `matcha`.`blocked_users` (
  `idBlocker` INT NOT NULL,
  `idBlocked` INT NOT NULL,
  INDEX `fk_blocked_users_idx` (`idBlocker` ASC),
  INDEX `fk_blocked_idx` (`idBlocked` ASC),
  CONSTRAINT `fk_blocker`
    FOREIGN KEY (`idBlocker`)
    REFERENCES `matcha`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blocked`
    FOREIGN KEY (`idBlocked`)
    REFERENCES `matcha`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`messages` ;

CREATE TABLE IF NOT EXISTS `matcha`.`messages` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `idsender` INT NOT NULL,
  `idreceiver` INT NOT NULL,
  `text` TEXT(500) NOT NULL,
  `notificated` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idmessage`),
  INDEX `fk_messages1_idx` (`idsender` ASC),
  INDEX `fk_messages2_idx` (`idreceiver` ASC),
  CONSTRAINT `fk_messages1`
    FOREIGN KEY (`idsender`)
    REFERENCES `matcha`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages2`
    FOREIGN KEY (`idreceiver`)
    REFERENCES `matcha`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `matcha`.`tags`
-- -----------------------------------------------------
START TRANSACTION;
USE `matcha`;
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'geek');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'piercing');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'optimist');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'pessimistic');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'vegan');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'omnivore');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'tall');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'short');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'overweight');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'thin');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'outgoing');
INSERT INTO `matcha`.`tags` (`idtags`, `tag_name`) VALUES (DEFAULT, 'shy');

COMMIT;

